#version 460

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct SHData {
    vec4 coeffs[9];
};

layout(std430, binding = 0) readonly buffer SHBuffer {
    SHData shData[];
};

layout(rgba32f, binding = 1) uniform imageCubeArray envMap;


#define PI 3.1415926535897932384626433832795

vec3 GetNormal(ivec2 pixel, int face, float size)
{
    float u = 2.0 * ((pixel.x + 0.5) / size) - 1.0;
    float v = 2.0 * ((pixel.y + 0.5) / size) - 1.0;
    
    vec3 dirRaw;
    switch(face)
    {
        case 0: // +X
            dirRaw = vec3( 1.0, -v, -u );
            break;
        case 1: // -X
            dirRaw = vec3(-1.0, -v,  u );
            break;
        case 2: // +Y
            dirRaw = vec3( u,  1.0,  v );
            break;
        case 3: // -Y
            dirRaw = vec3( u, -1.0, -v );
            break;
        case 4: // +Z
            dirRaw = vec3( u, -v,  1.0 );
            break;
        case 5: // -Z
            dirRaw = vec3( u,  v, -1.0 );
            break;
        default:
            dirRaw = vec3(0.0, 0.0, 0.0);
    }
    
    return normalize(dirRaw);
}

vec3 SampleSH(vec3 N, uint probeIndex)
{
	const float c0 = 0.282095;
	const float c1 = 0.488603;
	const float c2 = 1.092548;
	const float c3 = 0.315392;
	const float c4 = 0.546274;

	vec4 coeffs[9] = shData[probeIndex].coeffs;

    float x = N.x;
    float y = N.y;
    float z = N.z;
    
    float shBasis[9];
    shBasis[0] = c0;             // Y00
    shBasis[1] = c1 * y;         // Y1-1
    shBasis[2] = c1 * z;         // Y10
    shBasis[3] = c1 * x;         // Y11
    shBasis[4] = c2 * x * y;     // Y2-2
    shBasis[5] = c2 * y * z;     // Y2-1
    shBasis[6] = c3 * (3.0*z*z - 1.0); // Y20
    shBasis[7] = c2 * x * z;     // Y21
    shBasis[8] = c4 * (x*x - y*y); // Y22

    vec3 result = vec3(0.0);
    for (int i = 0; i < 9; i++) {
        result += coeffs[i].xyz * shBasis[i];
    }

	return max(result, vec3(0.0));
}

// Converts SHs to cubemaps for debugging
void main()
{
    uint face = uint(gl_GlobalInvocationID.z) % 6;
    ivec3 texelCoords = ivec3(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y, face);
    uint probeIndex = uint(gl_GlobalInvocationID.z / 6);

    vec3 N = GetNormal(texelCoords.xy, int(texelCoords.z), 512.0);

    vec3 shSample = SampleSH(N, probeIndex);

    imageStore(envMap, texelCoords, vec4(shSample, 1.0));
}